import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';

import { FaArrowRight, FaBeer, FaEnvelope, FaLocationArrow, FaPhone, FaShoppingCart, FaStar, FaStarHalf, FaUser, FaUserAltSlash } from "react-icons/fa";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
const Details = () => {
 
  const router=useRouter()
    const houseId=router.query._id
    const [details,setDetails]=useState({})
    useEffect(()=>{
        fetch(`https://renthouse-backend.onrender.com/house/${houseId}`)
        .then(res=>res.json())
        .then(data=>setDetails(data))
    },[])
   
    
    return (
      <>
      
      <div className='section-bg p-5'>
            <h3 className='heading-text text-white p-5'>House Details</h3>
            <p className='text-success fw-bold ps-5'><Link href="/" className='text-primary'>Home</Link><FaArrowRight/>House Details</p>
    </div>
      
      
   
        <div className='container'>
      <Head>
        <title>RENT House Details</title>
        <meta name="SearchHouse" content="Generated by Asad tech" />
        
      </Head>
    <div className='row shadow rounded'>
      <div className='col-md-8 p-5'>

     <ToastContainer/>

 
     
    
      <img src={details?.img}  class="img-fluid rounded-start" alt="House"/>
    
   
    
      <div class="card-body">
        <h6 class="card-title"><span className='text-danger'>Product Name</span>: {details?.title}</h6>
        <h6 class="card-title"><span className='text-danger'>Product Category</span>: {details?.category}</h6>
        <h6 class="card-title"><span className='text-danger'>Product Price</span>: {details?.price}<span className='fs-3'>৳</span></h6>
        <p class="card-text"><span className='fw-bold text-danger'>Details</span>:{details?.description}</p>
       
        
      
    </div>
    </div>

<div className='col-md-4 pt-5 pb-5 '>


<form  className='card p-3'>
  <div className='d-flex'>
  <span className='rounded bg-light p-2 mx-auto'><FaUser className='fs-1 p-1'/></span>
  </div>
  <p className='text-center fw-bold pt-1'>{details?.name}</p>
  <small className='text-center'>Building Owner</small>
  <p className='text-center'>
    <small className='pe-1'>4.8</small>
    <FaStar className='text-warning'/>
    <FaStar className='text-warning'/>
    <FaStar className='text-warning'/>
    <FaStar className='text-warning'/>
    <FaStarHalf className='text-warning'/>
    <small>(50)</small>
  </p>
  <hr/>
  <div className="form-group">
    <label for="exampleFormControlInput1">Your Name</label>
    <input type="name" name='name' className="form-control w-75" id="exampleFormControlInput1"/>
  </div>
  
  <div className="form-group">
    <label for="exampleFormControlInput1">Your Email</label>
    <input type="email" name='email' className="form-control w-75" id="exampleFormControlInput1"/>
  </div>
  <div className="form-group">
    <label for="exampleFormControlInput1">Your Message</label>
    <textarea  name='message' className="form-control w-75" id="exampleFormControlInput1"/>
  </div>
  
  <div className="form-group">
 <button className='btn btn-danger fw-bold mt-3'>Send Message</button>
  </div>
  <hr/>
  <div>
    <h6>Owner Contact Info</h6>
    <p>
      <FaLocationArrow className='text-warning'/>
      <span className='ps-1'>Address</span>
      <br/>
      <small className='ps-3 text-muted'>{details?.location}</small>
    </p>
    <p>
      <FaPhone className='text-warning'/>
      <span className='ps-1'>Phone</span>
      <br/>
      <small className='ps-3 text-muted'>{details?.phone}</small>
    </p>
    <p>
      <FaEnvelope className='text-warning'/>
      <span className='ps-1'>Email</span>
      <br/>
      <small className='ps-3 text-muted'>{details?.email}</small>
    </p>
  </div>
</form>
</div>
</div>  
        </div>
        </>
    );
};

export default Details;