import Script from 'next/script'
import '../styles/globals.css'
import Navbar from './Navbar'
import Head from 'next/head'
import Footer from './Footer'
import { FaSearch } from 'react-icons/fa'

function MyApp({ Component, pageProps }) {
  return<>
   <div className=''>
  <Head>
     <title>Search House</title>
        <meta name="this is Rent House Website" content="Generated by AsadTEch" />
      {/* bootstrap css cdn*/}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
      </Head>
      {/* bootstrap js cdn*/}
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></Script>
     
  <Navbar/>
  

  <Component {...pageProps} />

<Footer/>
</div>
 
  </>
}

export default MyApp
